[train]
lr = 0.0001
gpu = 0
epoch = 10
ar = 2.5
bs = 128
seed = 1
lradj = cosine

[data]
ws = 128
ic = 55
ds = MSL
dp = ./dataset/MSL

[param]
d_model = 128
dropout = 0.1
wavelet_name = db2
wavelet_level = 3
num_prototypes = 12
proto_top_k = 1
n_heads = 4
use_revin = 0
lambda_weight = 1
scale_patch_len = 8
scale_patch_stride_mode = half
encoder_layers = 3

[model]
model_name = MDAD
mode = tes
msp = ./checkpoints/MSL
